# Base configs
baseurl: "https://www.evgheniiloctev.art"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "-"

# UI configs
title: "Evghenii Loctev"
subtitle: "Portfolio"
author: "Evghenii Loctev"
header:
 title: "Evghenii Loctev"
 subtitle: "Creative Director"
footer:
 name: "Hello! My name is Evghenii Loctev"
 bio: "Creative director who manages projects collaboratively and in an organized manner. A qualified professional with six years of experience in CG, started as 3D Generalist. Good at gathering ideas, leading design teams, keeping to deadlines, and fixing issues. Open to new ideas, a self-motivated person who wants to keep learning."
 web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: "https://www.linkedin.com/in/evgheniiloctev/"
  
